---
- name: copy schema.sql into ~/schema.sql
  copy:
    src: schema.sql
    dest: ~/schema.sql
    mode: 0600

- name: create database
  mysql_db:
    name: "{{ servers.db.database }}"
    state: present
  notify:
    - import schema.sql

- name: create user for database
  mysql_user:
    host: "{{ servers.db.host }}"
    name: "{{ servers.db.username }}"
    password: "{{ servers.db.password }}"
    priv: "{{ servers.db.database }}.*:ALL"
    state: present

- name: ensure mysql daemon is started
  service:
    name: mysql
    state: started

- name: configure mysql daemon (mysqld.cnf)
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/conf.d/mysqld.cnf
  notify:
    - restart mysql-server
