---
- name: install mysql-client
  sudo: True
  apt: update_cache=yes name=mysql-client

- name: install libpython-dev
  sudo: True
  apt: name=libpython-dev

- name: install libmysqlclient-dev
  sudo: True
  apt: name=libmysqlclient-dev

- name: install python2.7
  sudo: True
  apt: name=python2.7

- name: install virtualenv
  sudo: True
  apt: name=python-virtualenv

- name: install python-mysqldb
  sudo: True
  apt: name=python-mysqldb

- name: install python-pip
  sudo: True
  apt: name=python-pip

- name: install log-reader requirements.txt
  pip: virtualenv=/vagrant/log-reader/venv requirements=/vagrant/log-reader/requirements.txt

- name: install apt-transport-https
  sudo: True
  apt: name=apt-transport-https

- name: add varnish-cache.org GPG-key
  sudo: True
  apt_key: url=https://repo.varnish-cache.org/GPG-key.txt state=present

- name: add varnish-cache.org repository
  sudo: True
  apt_repository: repo="deb https://repo.varnish-cache.org/ubuntu/ trusty varnish-4.0" state=present

- name: install varnish-cache
  sudo: True
  apt: name=varnish update_cache=yes
  notify:
    - restart varnish

- name: copy default.vcl configuration
  sudo: True
  template: force=yes src=templates/backend/default.vcl.j2 dest=/etc/varnish/default.vcl
  notify:
    - restart varnish

- name: ensure varnish is running
  sudo: True
  service: name=varnish state=running

- name: install siege
  apt: name=siege

- name: install siege-varnish service
  sudo: yes
  template: force=yes mode=0751 src=templates/backend/siege-varnish.service.j2 dest=/etc/systemd/system/siege-varnish.service

- name: restart siege-varnish service
  sudo: yes
  service: name=siege-varnish state=restarted