---
- name: install mysql-server
  sudo: yes
  apt: name=mysql-server update_cache=yes

- name: ensure mysql is running
  sudo: yes
  service: name=mysql state=running

- name: copy mysqld.cnf
  sudo: yes
  copy: mode=0644 src=files/db/mysqld.cnf dest=/etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
    - restart mysql

- name: install python-mysqldb module
  sudo: yes
  apt: name=python-mysqldb

- name: create microservice database
  sudo: yes
  mysql_db: name=microservice state=present

- name: add microservice user
  sudo: yes
  mysql_user: name=microservice password='AWe*apei9ue$s1u' host=% priv=microservice.*:ALL
  notify:
    - restart mysql

- name: copy schema.sql into /tmp
  copy: src=files/db/schema.sql dest=/tmp

- name: import mysql schema
  sudo: yes
  mysql_db: state=import name=microservice target=/tmp/schema.sql